import { getRegisteredAgent, TOOL_FAMILY_MAP } from '../db/agent-accessors.js';
import {
  resolveExecution,
  ExecutionResolverError,
} from './execution-resolver.js';
import {
  streamLlmResponse,
  type LlmProviderConfig,
  type LlmSecret,
  type LlmToolDefinition,
  type LlmMessage,
  type LlmContentBlock,
  type LlmStreamEvent,
  LlmClientError,
} from './llm-client.js';
import { TalkExecutorError } from '../talks/executor.js';

// ---------------------------------------------------------------------------
// Types: Execution Context and Events
// ---------------------------------------------------------------------------

/**
 * ExecutionContext encapsulates all Talk-related context provided to the agent.
 * For Main channel execution (context=null), this is omitted entirely.
 */
export interface ExecutionContext {
  /** System prompt prefix for this Talk (goal, rules, summary, sources) */
  systemPrompt: string;

  /** Tool definitions for reading Talk context (always included for Talk execution) */
  contextTools: LlmToolDefinition[];

  /** Tool definitions for data connectors bound to this Talk */
  connectorTools: LlmToolDefinition[];

  /** Conversation history for this Talk */
  history: LlmMessage[];
}

/**
 * ExecutionEvent is emitted during agent execution to stream progress to the caller.
 */
export type ExecutionEvent =
  | {
      type: 'started';
      runId: string;
      agentId: string;
      providerId: string;
      modelId: string;
    }
  | {
      type: 'text_delta';
      text: string;
    }
  | {
      type: 'tool_call';
      toolName: string;
      arguments: Record<string, unknown>;
    }
  | {
      type: 'tool_result';
      toolName: string;
      result: string;
      isError?: boolean;
    }
  | {
      type: 'awaiting_confirmation';
      confirmationId: string;
      toolName: string;
      actionSummary: string;
    }
  | {
      type: 'usage';
      inputTokens: number;
      outputTokens: number;
      estimatedCostUsd?: number;
    }
  | {
      type: 'completed';
      content: string;
      completion?: {
        completionStatus: 'complete' | 'incomplete';
        providerStopReason?: string | null;
        incompleteReason?: 'truncated' | 'empty' | 'unknown' | null;
      };
    }
  | {
      type: 'failed';
      errorCode: string;
      errorMessage: string;
      completion?: {
        completionStatus: 'complete' | 'incomplete';
        providerStopReason?: string | null;
        incompleteReason?: 'truncated' | 'empty' | 'unknown' | null;
      };
    }
  | {
      type: 'cancelled';
    };

/**
 * Final result of an agent execution.
 */
export interface AgentExecutionResult {
  /** The final content generated by the agent */
  content: string;

  /** Execution metadata */
  agentId: string;
  providerId: string;
  modelId: string;

  /** Token usage and estimated cost */
  usage?: {
    inputTokens: number;
    outputTokens: number;
    estimatedCostUsd?: number;
  };
  completion?: {
    completionStatus: 'complete' | 'incomplete';
    providerStopReason?: string | null;
    incompleteReason?: 'truncated' | 'empty' | 'unknown' | null;
  };
  /**
   * Provider-specific blobs to persist on the assistant message
   * (talk_messages.metadata_json) so the next turn can replay them.
   * Currently used by the codex_responses path to carry forward
   * encrypted reasoning items + assistant message items for
   * prefix-cache + chain-of-thought continuity.
   */
  providerData?: {
    codexReasoningItems?: Array<Record<string, unknown>>;
    codexMessageItems?: Array<Record<string, unknown>>;
  };
}

export const ALWAYS_ALLOWED_CONTEXT_TOOLS = new Set([
  'list_state',
  'read_context_source',
  'read_attachment',
  'read_state',
]);

const CLEAN_PROVIDER_STOP_REASONS = new Set([
  'stop',
  'end_turn',
  'stop_sequence',
]);

/**
 * Max number of times we'll silently retry an incomplete Codex
 * response before surfacing it as `incomplete_response`. Mirrors
 * hermes' 3-retry continuation budget. A Codex "incomplete" usually
 * means the model produced commentary or reasoning-only output and
 * needs one more turn to land on a final answer — feeding back the
 * encrypted reasoning items lets the backend keep its chain coherent.
 */
const MAX_CODEX_CONTINUATIONS = 3;

function normalizeProviderStopReason(value: string): string | null {
  const normalized = value.trim();
  return normalized.length > 0 ? normalized : null;
}

function buildIncompleteCompletion(input: {
  content: string;
  providerStopReason: string | null;
}): {
  completionStatus: 'incomplete';
  providerStopReason?: string | null;
  incompleteReason?: 'truncated' | 'empty' | 'unknown' | null;
  errorMessage: string;
} {
  const hasVisibleText = input.content.trim().length > 0;
  if (!hasVisibleText) {
    return {
      completionStatus: 'incomplete',
      providerStopReason: input.providerStopReason,
      incompleteReason: 'empty',
      errorMessage:
        'The model finished without producing a usable final response.',
    };
  }

  if (
    input.providerStopReason === 'length' ||
    input.providerStopReason === 'max_tokens'
  ) {
    return {
      completionStatus: 'incomplete',
      providerStopReason: input.providerStopReason,
      incompleteReason: 'truncated',
      errorMessage: `The model stopped before finishing its answer (provider stop reason: ${input.providerStopReason}).`,
    };
  }

  return {
    completionStatus: 'incomplete',
    providerStopReason: input.providerStopReason,
    incompleteReason: 'unknown',
    errorMessage: input.providerStopReason
      ? `The model stopped without a clean completion signal (provider stop reason: ${input.providerStopReason}).`
      : 'The model stopped without a clean completion signal.',
  };
}

// ---------------------------------------------------------------------------
// Main Execution Function
// ---------------------------------------------------------------------------

/**
 * Execute an agent with optional Talk context and streaming output.
 *
 * Flow:
 * 1. Load agent config (provider, model, tool permissions)
 * 2. Resolve provider credentials
 * 3. Filter tools by agent permissions (+ always include context tools if in Talk)
 * 4. Build LLM messages (system prompt + history + user message)
 * 5. Call LLM, stream events
 * 6. Handle tool loop: execute tools, append results, call LLM again (max 10 iterations)
 * 7. Handle fallback: if primary provider fails, try fallback steps
 * 8. Return result
 *
 * @param agentId - ID of the registered agent to execute
 * @param context - Talk execution context, or null for Main channel
 * @param userMessage - User's message to process
 * @param options - Execution options
 * @returns Final execution result
 */
export async function executeWithAgent(
  agentId: string,
  context: ExecutionContext | null,
  userMessage: string | LlmContentBlock[],
  options: {
    runId: string;
    userId: string;
    signal?: AbortSignal;
    emit?: (event: ExecutionEvent) => void;
    executeToolCall?: (
      toolName: string,
      args: Record<string, unknown>,
    ) => Promise<{ result: string; isError?: boolean }>;
    alwaysAllowedContextToolNames?: string[];
    maxToolIterations?: number;
    toolIterationLimitFallback?: string;
  },
): Promise<AgentExecutionResult> {
  const emit = options.emit || (() => {});

  // -----------
  // Step 1: Load agent config
  // -----------
  const agent = await getRegisteredAgent(agentId);
  if (!agent) {
    const errorCode = 'AGENT_NOT_FOUND';
    const errorMessage = `Agent ${agentId} not found`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  if (!agent.enabled) {
    const errorCode = 'AGENT_DISABLED';
    const errorMessage = `Agent ${agentId} is disabled`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  // -----------
  // Step 2: Resolve execution binding (provider config + credentials)
  //
  // This is delegated to execution-resolver.ts — the single source of truth
  // for merging agent config, provider config, and credential source.
  // See execution-resolver.ts for the full execution mode model.
  // -----------
  let providerConfig: LlmProviderConfig;
  let secret: LlmSecret;
  let defaultMaxOutputTokens: number | undefined;

  try {
    const binding = await resolveExecution(agent);
    providerConfig = binding.providerConfig;
    secret = binding.secret;
    defaultMaxOutputTokens = binding.defaultMaxOutputTokens;
  } catch (err) {
    if (err instanceof ExecutionResolverError) {
      emit({ type: 'failed', errorCode: err.code, errorMessage: err.message });
    } else {
      emit({
        type: 'failed',
        errorCode: 'EXECUTION_RESOLUTION_FAILED',
        errorMessage: String(err),
      });
    }
    throw err;
  }

  // -----------
  // Step 3: Filter tools by agent permissions
  // -----------
  // tool_permissions_json is jsonb in postgres — round-trips as a parsed
  // object, not a string. No JSON.parse needed in the cloud path.
  const agentPermissions: Record<string, boolean> = agent.tool_permissions_json;

  // Resolve enabled tools from TOOL_FAMILY_MAP
  const enabledToolNames = new Set<string>();
  const alwaysAllowedToolNames = new Set(ALWAYS_ALLOWED_CONTEXT_TOOLS);
  for (const toolName of options.alwaysAllowedContextToolNames || []) {
    alwaysAllowedToolNames.add(toolName);
  }
  const connectorsEnabled = agentPermissions['connectors'] === true;
  for (const [family, enabled] of Object.entries(agentPermissions)) {
    if (enabled === true) {
      const familyTools = TOOL_FAMILY_MAP[family] || [];
      for (const tool of familyTools) {
        enabledToolNames.add(tool);
      }
    }
  }

  /**
   * Check whether a tool is permitted for this agent.
   * - Context-internal tools in ALWAYS_ALLOWED_CONTEXT_TOOLS are always allowed.
   * - Connector tools (connector_*) are allowed if the 'connectors' family is enabled.
   * - All other tools are allowed only if they appear in enabledToolNames.
   */
  function isToolPermitted(toolName: string): boolean {
    if (alwaysAllowedToolNames.has(toolName)) {
      return true; // Always allowed — Talk-internal context access
    }
    if (toolName.startsWith('connector_')) {
      return connectorsEnabled;
    }
    return enabledToolNames.has(toolName);
  }

  // Build tool array, filtering by agent's tool permissions.
  const tools: LlmToolDefinition[] = [];

  if (context) {
    for (const tool of context.contextTools) {
      if (isToolPermitted(tool.name)) {
        tools.push(tool);
      }
    }
    for (const tool of context.connectorTools) {
      if (isToolPermitted(tool.name)) {
        tools.push(tool);
      }
    }
  }

  // TODO: Add agent's own tools here once they're available in the execution context
  // For now, assume they're passed via executeToolCall handler

  // -----------
  // Step 4: Build LLM messages
  // -----------
  const messages: LlmMessage[] = [];

  // Build system prompt and push as first message
  let systemPrompt = '';
  if (context) {
    // Talk context + agent system prompt
    systemPrompt = context.systemPrompt;
    if (agent.system_prompt) {
      systemPrompt += '\n\n' + agent.system_prompt;
    }
  } else {
    // Main channel: just agent's system prompt
    systemPrompt = agent.system_prompt || '';
  }

  if (systemPrompt) {
    messages.push({ role: 'system', content: systemPrompt });
  }

  // Add Talk history if in Talk context
  if (context && context.history.length > 0) {
    messages.push(...context.history);
  }

  // Add user message
  messages.push({
    role: 'user',
    content: userMessage,
  });

  // -----------
  // Step 5: Stream LLM response
  // -----------
  emit({
    type: 'started',
    runId: options.runId,
    agentId,
    providerId: agent.provider_id,
    modelId: agent.model_id,
  });

  let finalContent = '';
  let accumulatedTokens = {
    inputTokens: 0,
    outputTokens: 0,
    estimatedCostUsd: 0,
  };
  let lastProviderStopReason: string | null = null;
  let usedToolIterationFallback = false;
  // Track the most recent turn's provider_data so the executor can
  // persist it on the assistant talk_message. Only the FINAL turn's
  // codex items are kept (mid-loop tool-call turns get their reasoning
  // replaced on the next iteration anyway).
  let latestProviderData: AgentExecutionResult['providerData'] | undefined;

  const maxToolIterations = Math.max(1, options.maxToolIterations ?? 10);
  let codexContinuationCount = 0;

  try {
    for (let iteration = 0; iteration < maxToolIterations; iteration++) {
      const stream = streamLlmResponse(
        providerConfig,
        secret,
        agent.model_id,
        messages,
        {
          tools,
          maxOutputTokens: defaultMaxOutputTokens,
          signal: options.signal,
        },
      );

      // Accumulate this turn's content and tool calls from the stream
      let turnTextContent = '';
      const pendingToolCalls = new Map<
        string,
        { name: string; argumentsJson: string }
      >();
      let stopReason = 'end_turn';

      for await (const event of stream) {
        if (options.signal?.aborted) {
          emit({ type: 'cancelled' });
          const abortErr =
            options.signal.reason instanceof Error
              ? options.signal.reason
              : Object.assign(new Error('Agent execution was cancelled'), {
                  name: 'AbortError',
                });
          throw abortErr;
        }

        if (event.type === 'text_delta') {
          turnTextContent += event.text;
          emit({ type: 'text_delta', text: event.text || '' });
        } else if (event.type === 'tool_call_start') {
          if (event.toolCall) {
            pendingToolCalls.set(event.toolCall.id, {
              name: event.toolCall.name,
              argumentsJson: '',
            });
          }
        } else if (event.type === 'tool_call_delta') {
          if (event.toolCall) {
            const current = pendingToolCalls.get(event.toolCall.id);
            if (current) {
              if (event.toolCall.argumentsDelta) {
                current.argumentsJson += event.toolCall.argumentsDelta;
              }
              if (event.toolCall.arguments) {
                current.argumentsJson = event.toolCall.arguments;
              }
            }
          }
        } else if (event.type === 'done') {
          stopReason = event.stopReason || 'end_turn';
        } else if (event.type === 'usage') {
          accumulatedTokens = {
            inputTokens:
              accumulatedTokens.inputTokens + (event.usage?.inputTokens || 0),
            outputTokens:
              accumulatedTokens.outputTokens + (event.usage?.outputTokens || 0),
            estimatedCostUsd: 0,
          };
          emit({
            type: 'usage',
            inputTokens: event.usage?.inputTokens || 0,
            outputTokens: event.usage?.outputTokens || 0,
            estimatedCostUsd: 0,
          });
        } else if (event.type === 'provider_data') {
          if (event.providerData) {
            latestProviderData = event.providerData;
          }
        }
      }

      finalContent += turnTextContent;
      lastProviderStopReason = normalizeProviderStopReason(stopReason);
      const reachedToolIterationLimit = iteration === maxToolIterations - 1;

      // If no tool calls or no executeToolCall callback, we're done.
      // Anthropic stop reason: 'tool_use', OpenAI finish reason: 'tool_calls'
      const isToolUseStop =
        stopReason === 'tool_use' || stopReason === 'tool_calls';
      if (
        pendingToolCalls.size === 0 ||
        !options.executeToolCall ||
        !isToolUseStop
      ) {
        // Codex continuation retry: an `incomplete` response with
        // captured encrypted reasoning means the model produced
        // commentary or thinking-only output and needs one more turn.
        // Feed the partial assistant message + reasoning blob back in
        // so the backend continues from where it left off. Bounded by
        // MAX_CODEX_CONTINUATIONS; the iteration counter is rewound so
        // the continuation doesn't burn the tool-iteration budget.
        const codexShouldContinue =
          providerConfig.apiFormat === 'codex_responses' &&
          stopReason === 'incomplete' &&
          Boolean(
            latestProviderData?.codexReasoningItems?.length ||
            latestProviderData?.codexMessageItems?.length,
          ) &&
          codexContinuationCount < MAX_CODEX_CONTINUATIONS;
        if (codexShouldContinue) {
          codexContinuationCount += 1;
          messages.push({
            role: 'assistant',
            content: turnTextContent || '',
            providerData: latestProviderData,
          });
          iteration -= 1;
          continue;
        }
        break;
      }

      // Build assistant message with text + tool_use content blocks
      const assistantContent: LlmContentBlock[] = [];
      if (turnTextContent) {
        assistantContent.push({ type: 'text', text: turnTextContent });
      }
      for (const [id, call] of Array.from(pendingToolCalls.entries())) {
        let parsedInput: unknown = {};
        try {
          parsedInput = call.argumentsJson
            ? JSON.parse(call.argumentsJson)
            : {};
        } catch {
          parsedInput = {};
        }
        assistantContent.push({
          type: 'tool_use',
          id,
          name: call.name,
          input: parsedInput,
        });
      }
      messages.push({ role: 'assistant', content: assistantContent });

      // Execute each tool call and collect results
      const toolResults: Array<{
        id: string;
        name: string;
        result: string;
        isError: boolean;
      }> = [];
      for (const [id, call] of Array.from(pendingToolCalls.entries())) {
        let parsedArgs: Record<string, unknown> = {};
        try {
          parsedArgs = call.argumentsJson ? JSON.parse(call.argumentsJson) : {};
        } catch {
          parsedArgs = {};
        }

        emit({
          type: 'tool_call',
          toolName: call.name,
          arguments: parsedArgs,
        });

        try {
          const { result, isError } = await options.executeToolCall(
            call.name,
            parsedArgs,
          );
          emit({
            type: 'tool_result',
            toolName: call.name,
            result,
            isError,
          });
          toolResults.push({
            id,
            name: call.name,
            result,
            isError: !!isError,
          });
        } catch (err) {
          const errorMsg = String(err);
          emit({
            type: 'tool_result',
            toolName: call.name,
            result: errorMsg,
            isError: true,
          });
          toolResults.push({
            id,
            name: call.name,
            result: errorMsg,
            isError: true,
          });
        }
      }

      // Append tool results as messages.
      // For Anthropic: tool_result blocks inside a single role:'tool' message
      //   (buildAnthropicRequest converts role:'tool' with LlmContentBlock[] to
      //    a user message with tool_result blocks)
      // For OpenAI: individual role:'tool' messages with toolCallId
      //   (buildOpenAiRequest handles role:'tool' with string content + toolCallId)
      // Use structured content blocks — both builders handle this format.
      if (providerConfig.apiFormat === 'openai_chat_completions') {
        // OpenAI expects separate tool messages per tool call
        for (const tr of toolResults) {
          messages.push({
            role: 'tool',
            content: tr.result,
            toolCallId: tr.id,
          });
        }
      } else {
        // Anthropic: structured tool_result blocks
        const toolResultBlocks: LlmContentBlock[] = toolResults.map((tr) => ({
          type: 'tool_result' as const,
          toolUseId: tr.id,
          content: tr.result,
          isError: tr.isError,
        }));
        messages.push({ role: 'tool', content: toolResultBlocks });
      }

      if (reachedToolIterationLimit) {
        if (options.toolIterationLimitFallback) {
          finalContent = options.toolIterationLimitFallback;
          usedToolIterationFallback = true;
        }
        break;
      }

      // Reset turn text for next iteration — the LLM will produce new content
      // finalContent already accumulated, next turn appends more
    }
  } catch (err) {
    if (err instanceof LlmClientError) {
      // TODO: Implement fallback logic here
      // For now, just fail
      emit({
        type: 'failed',
        errorCode: err.failureClass || 'LLM_ERROR',
        errorMessage: err.message,
      });
      throw err;
    }
    throw err;
  }

  // -----------
  // Step 6: Emit completion
  // -----------
  if (!usedToolIterationFallback) {
    const finalContentTrimmed = finalContent.trim();
    const completedCleanly =
      finalContentTrimmed.length > 0 &&
      Boolean(
        lastProviderStopReason &&
        CLEAN_PROVIDER_STOP_REASONS.has(lastProviderStopReason),
      );

    if (!completedCleanly) {
      const incomplete = buildIncompleteCompletion({
        content: finalContent,
        providerStopReason: lastProviderStopReason,
      });
      emit({
        type: 'failed',
        errorCode: 'incomplete_response',
        errorMessage: incomplete.errorMessage,
        completion: incomplete,
      });
      throw new TalkExecutorError(
        'incomplete_response',
        incomplete.errorMessage,
        {
          metadata: incomplete,
        },
      );
    }
  }

  const completion = {
    completionStatus: 'complete' as const,
    providerStopReason: lastProviderStopReason,
    incompleteReason: null,
  };
  emit({
    type: 'completed',
    content: finalContent,
    completion,
  });

  return {
    content: finalContent,
    agentId,
    providerId: agent.provider_id,
    modelId: agent.model_id,
    usage: accumulatedTokens,
    completion,
    providerData: latestProviderData,
  };
}
