import {
  getRegisteredAgent,
  type EffectiveToolAccess,
  type RegisteredAgentRecord,
} from '../db/agent-accessors.js';
import { ensureRunnableModel } from './runtime-model-guard.js';
import {
  resolveExecution,
  ExecutionResolverError,
  type ExecutionCredentialScope,
} from './execution-resolver.js';
import {
  streamLlmResponse,
  type LlmProviderConfig,
  type LlmSecret,
  type LlmToolDefinition,
  type LlmMessage,
  type LlmContentBlock,
  type LlmStreamEvent,
  LlmClientError,
} from './llm-client.js';
import { TalkExecutorError } from '../talks/executor.js';
import type { DeadlineBudget } from '../talks/deadline-budget.js';

// ---------------------------------------------------------------------------
// Types: Execution Context and Events
// ---------------------------------------------------------------------------

/**
 * ExecutionContext encapsulates all Talk-related context provided to the agent.
 * For Main channel execution (context=null), this is omitted entirely.
 */
export interface ExecutionContext {
  /** System prompt prefix for this Talk (goal, rules, summary, sources) */
  systemPrompt: string;

  /** Tool definitions for reading Talk context (always included for Talk execution) */
  contextTools: LlmToolDefinition[];

  /** Tool definitions for data connectors bound to this Talk */
  connectorTools: LlmToolDefinition[];

  /** Conversation history for this Talk */
  history: LlmMessage[];
}

/**
 * ExecutionEvent is emitted during agent execution to stream progress to the caller.
 */
export type ExecutionEvent =
  | {
      type: 'started';
      runId: string;
      agentId: string;
      providerId: string;
      modelId: string;
    }
  | {
      type: 'text_delta';
      text: string;
    }
  | {
      type: 'tool_call';
      toolName: string;
      arguments: Record<string, unknown>;
    }
  | {
      type: 'tool_result';
      toolName: string;
      result: string;
      isError?: boolean;
      durationMs?: number;
    }
  | {
      type: 'awaiting_confirmation';
      confirmationId: string;
      toolName: string;
      actionSummary: string;
    }
  | {
      type: 'usage';
      inputTokens: number;
      outputTokens: number;
      estimatedCostUsd?: number;
    }
  | {
      type: 'completed';
      content: string;
      completion?: {
        completionStatus: 'complete' | 'incomplete';
        providerStopReason?: string | null;
        incompleteReason?: 'truncated' | 'empty' | 'unknown' | null;
      };
    }
  | {
      type: 'failed';
      errorCode: string;
      errorMessage: string;
      completion?: {
        completionStatus: 'complete' | 'incomplete';
        providerStopReason?: string | null;
        incompleteReason?: 'truncated' | 'empty' | 'unknown' | null;
      };
    }
  | {
      type: 'cancelled';
    };

/**
 * Final result of an agent execution.
 */
export interface AgentExecutionResult {
  /** The final content generated by the agent */
  content: string;

  /** Execution metadata */
  agentId: string;
  providerId: string;
  modelId: string;

  /** Token usage and estimated cost */
  usage?: {
    inputTokens: number;
    outputTokens: number;
    estimatedCostUsd?: number;
  };
  completion?: {
    completionStatus: 'complete' | 'incomplete';
    providerStopReason?: string | null;
    incompleteReason?: 'truncated' | 'empty' | 'unknown' | null;
  };
  /**
   * Provider-specific blobs to persist in the trusted replay store so
   * the next turn can replay them. Currently used by the codex_responses
   * path to carry forward encrypted reasoning items + assistant message
   * items for prefix-cache + chain-of-thought continuity.
   */
  providerData?: {
    codexReasoningItems?: Array<Record<string, unknown>>;
    codexMessageItems?: Array<Record<string, unknown>>;
  };
}

export interface AgentExecutionOptions {
  runId: string;
  userId: string;
  signal?: AbortSignal;
  emit?: (event: ExecutionEvent) => void;
  executeToolCall?: (
    toolName: string,
    args: Record<string, unknown>,
  ) => Promise<{ result: string; isError?: boolean }>;
  alwaysAllowedContextToolNames?: string[];
  maxToolIterations?: number;
  toolIterationLimitFallback?: string;
  /**
   * When true, set provider-specific `tool_choice=required` on the
   * FIRST iteration of the tool-calling loop. Subsequent iterations
   * fall back to the default 'auto' — once the agent has been pushed
   * into picking a tool, we let it decide whether to call more tools
   * or settle on a final assistant turn.
   */
  forceToolUseOnFirstIteration?: boolean;
  /**
   * Snapshot of the credential kind the resolver should pick for this run.
   * Null/undefined falls back to the live agent value.
   */
  credentialKindSnapshot?: 'api_key' | 'subscription' | null;
  /**
   * Explicit credential scope for provider secrets. Runtime paths fail closed
   * for personal/workspace credentials when this is omitted.
   */
  credentialScope?: ExecutionCredentialScope | null;
  /**
   * The Talk's effective tool set for this turn. Absent => no non-internal
   * tools are exposed.
   */
  effectiveTools?: EffectiveToolAccess[];
  /**
   * Run-scoped deadline budget (T6). When present, the tool loop stops at a
   * step boundary once the run's external-await budget is exhausted instead of
   * starting another LLM + tool round. Tool legs (web_search) draw their own
   * per-step caps from the same budget. Absent for direct/test callers.
   */
  budget?: DeadlineBudget;
}

export const ALWAYS_ALLOWED_CONTEXT_TOOLS = new Set([
  'read_source',
  // Content-feature edit tool — registered only when
  // the Talk has an attached Content doc (`hasContent === true`). Never
  // appears in any tool family, so
  // without this allowlist it gets silently filtered out for every
  // agent.
  'apply_content_edit',
]);

/**
 * Tools that are SAFE TO RUN CONCURRENTLY with each other within a single
 * assistant turn's tool batch. A maximal run of CONSECUTIVE listed tools
 * executes in parallel (bounded by READ_ONLY_TOOL_CONCURRENCY); every other
 * tool is a barrier that runs sequentially. See the dispatch loop below.
 *
 * Membership is an EXPLICIT, per-tool correctness assertion. There is NO name,
 * prefix, or family inference: a tool absent from this set runs sequentially
 * even if it "looks" read-only. To add a tool here it must be:
 *   - side-effect-free on EVERY path, including error/retry paths (it mutates
 *     no Talk / document / external / stored-credential state — reruns and
 *     concurrent siblings are observationally equivalent), and
 *   - safe to run concurrently with its own siblings.
 *
 * Deliberately conservative — only the two tools we can assert are pure:
 *   - read_source: a single SELECT over context_sources.
 *   - web_search: resolves credentials in a short tx that COMMITS before the
 *     provider fetch (T2/#622) and never mutates stored secrets; the fetch is
 *     the latency parallelism actually hides.
 * The Google read tools are NOT listed: their 401-retry path can refresh OR
 * DELETE the stored OAuth credential and bypasses the in-flight-refresh
 * dedupe (google-drive-tools.ts -> google-tools-service.ts), so concurrent
 * Google reads can stampede a credential write. Parallelizing them is a
 * follow-up gated on routing that retry through the deduped refresh.
 *
 * This set changes ONLY execution concurrency. Results are always appended to
 * the message history in batch (tool_use id) order regardless of completion
 * order, so the prefix stays byte-stable for prompt caching (T4 / Lane A). Do
 * not use this set to reorder results.
 */
export const READ_ONLY_PARALLELIZABLE_TOOLS = new Set<string>([
  'read_source',
  'web_search',
]);

/**
 * Upper bound on read-only tool calls executed concurrently within one
 * contiguous run. Caps provider-quota and request-DB connection-queue pressure
 * when a model emits a large tool batch in a single turn (a hostile or confused
 * model can request many web_search calls at once). Small because the shared
 * request DB client is max:1 and search providers rate-limit.
 */
export const READ_ONLY_TOOL_CONCURRENCY = 6;

/**
 * Run `fn` over `items` with at most `limit` concurrent executions, returning
 * results in INPUT order (never completion order). Used to bound and order the
 * parallel execution of a contiguous run of read-only tool calls so the
 * appended results stay byte-stable for prompt caching.
 */
async function runBoundedInOrder<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length);
  let cursor = 0;
  const worker = async (): Promise<void> => {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await fn(items[index]);
    }
  };
  const workerCount = Math.min(Math.max(1, limit), items.length);
  await Promise.all(Array.from({ length: workerCount }, () => worker()));
  return results;
}

const CLEAN_PROVIDER_STOP_REASONS = new Set([
  'stop',
  'end_turn',
  'stop_sequence',
]);

/**
 * Max number of times we'll silently retry an incomplete Codex
 * response before surfacing it as `incomplete_response`. Mirrors
 * hermes' 3-retry continuation budget. A Codex "incomplete" usually
 * means the model produced commentary or reasoning-only output and
 * needs one more turn to land on a final answer — feeding back the
 * encrypted reasoning items lets the backend keep its chain coherent.
 */
const MAX_CODEX_CONTINUATIONS = 3;

function normalizeProviderStopReason(value: string): string | null {
  const normalized = value.trim();
  return normalized.length > 0 ? normalized : null;
}

function buildIncompleteCompletion(input: {
  content: string;
  providerStopReason: string | null;
}): {
  completionStatus: 'incomplete';
  providerStopReason?: string | null;
  incompleteReason?: 'truncated' | 'empty' | 'unknown' | null;
  errorMessage: string;
} {
  const hasVisibleText = input.content.trim().length > 0;
  if (!hasVisibleText) {
    return {
      completionStatus: 'incomplete',
      providerStopReason: input.providerStopReason,
      incompleteReason: 'empty',
      errorMessage:
        'The model finished without producing a usable final response.',
    };
  }

  if (
    input.providerStopReason === 'length' ||
    input.providerStopReason === 'max_tokens'
  ) {
    return {
      completionStatus: 'incomplete',
      providerStopReason: input.providerStopReason,
      incompleteReason: 'truncated',
      errorMessage: `The model stopped before finishing its answer (provider stop reason: ${input.providerStopReason}).`,
    };
  }

  return {
    completionStatus: 'incomplete',
    providerStopReason: input.providerStopReason,
    incompleteReason: 'unknown',
    errorMessage: input.providerStopReason
      ? `The model stopped without a clean completion signal (provider stop reason: ${input.providerStopReason}).`
      : 'The model stopped without a clean completion signal.',
  };
}

// ---------------------------------------------------------------------------
// Main Execution Function
// ---------------------------------------------------------------------------

/**
 * Execute an agent with optional Talk context and streaming output.
 *
 * Flow:
 * 1. Load agent config (provider, model, tool permissions)
 * 2. Resolve provider credentials
 * 3. Filter tools by agent permissions (+ always include context tools if in Talk)
 * 4. Build LLM messages (system prompt + history + user message)
 * 5. Call LLM, stream events
 * 6. Handle tool loop: execute tools, append results, call LLM again (max 10 iterations)
 * 7. Handle fallback: if primary provider fails, try fallback steps
 * 8. Return result
 *
 * @param agentId - ID of the registered agent to execute
 * @param context - Talk execution context, or null for Main channel
 * @param userMessage - User's message to process
 * @param options - Execution options
 * @returns Final execution result
 */
export async function executeWithAgent(
  agentId: string,
  context: ExecutionContext | null,
  userMessage: string | LlmContentBlock[],
  options: AgentExecutionOptions,
): Promise<AgentExecutionResult> {
  const emit = options.emit || (() => {});

  // -----------
  // Step 1: Load agent config
  // -----------
  const agent = await getRegisteredAgent(agentId);
  if (!agent) {
    const errorCode = 'AGENT_NOT_FOUND';
    const errorMessage = `Agent ${agentId} not found`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  if (!agent.enabled) {
    const errorCode = 'AGENT_DISABLED';
    const errorMessage = `Agent ${agentId} is disabled`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  // Run-time safety net: swap a retired model to a served one before we
  // resolve the binding and stream. Fail-open and mutates `agent` in place,
  // so the binding's default-output query, the `started` event, the stream
  // call, and the returned modelId below all use the live model. Redundant
  // for Talk runs (the executor already swapped via resolveTalkAgent, and we
  // re-load the upgraded row here) but makes executeWithAgent correct for any
  // caller that reaches it directly. See runtime-model-guard.ts.
  await ensureRunnableModel(agent, {
    credentialScope: options.credentialScope ?? null,
  });

  return executeWithResolvedAgent(agent, context, userMessage, options);
}

/**
 * Execute an already-resolved agent record.
 *
 * Greenfield Talk runs execute from immutable `talk_agent_snapshots`; this
 * entry point lets that path reuse the router's credential resolution,
 * tool-loop, streaming, and incomplete-response handling without reloading
 * the mutable legacy registered-agent row.
 */
export async function executeWithResolvedAgent(
  agent: RegisteredAgentRecord,
  context: ExecutionContext | null,
  userMessage: string | LlmContentBlock[],
  options: AgentExecutionOptions,
): Promise<AgentExecutionResult> {
  const emit = options.emit || (() => {});
  const agentId = agent.id;

  if (!agent.enabled) {
    const errorCode = 'AGENT_DISABLED';
    const errorMessage = `Agent ${agentId} is disabled`;
    emit({ type: 'failed', errorCode, errorMessage });
    throw new Error(errorMessage);
  }

  // -----------
  // Step 2: Resolve execution binding (provider config + credentials)
  //
  // This is delegated to execution-resolver.ts — the single source of truth
  // for merging agent config, provider config, and credential source.
  // See execution-resolver.ts for the full execution mode model.
  // -----------
  let providerConfig: LlmProviderConfig;
  let secret: LlmSecret;
  let defaultMaxOutputTokens: number | undefined;

  try {
    const binding = await resolveExecution(agent, {
      credentialKindSnapshot: options.credentialKindSnapshot,
      credentialScope: options.credentialScope,
    });
    providerConfig = binding.providerConfig;
    secret = binding.secret;
    defaultMaxOutputTokens = binding.defaultMaxOutputTokens;
  } catch (err) {
    if (err instanceof ExecutionResolverError) {
      emit({ type: 'failed', errorCode: err.code, errorMessage: err.message });
    } else {
      emit({
        type: 'failed',
        errorCode: 'EXECUTION_RESOLUTION_FAILED',
        errorMessage: String(err),
      });
    }
    throw err;
  }

  // -----------
  // Step 3: Filter tools by the Talk's effective tool set
  // -----------
  // Tools are a property of the Talk, resolved upstream by
  // getEffectiveToolsForAgent (talkActive ∩ light ∩ userPermission) and passed
  // in as `effectiveTools`. When absent (ad-hoc/direct callers, tests) default
  // to NO tools — fail safe, never silently all-light. This is the single
  // source of truth for which tool DEFINITIONS the model sees, matching the
  // executor's execution-time gate so we never show a tool we'd then block.
  const effectiveTools = options.effectiveTools ?? [];

  const enabledToolNames = new Set<string>();
  const alwaysAllowedToolNames = new Set(ALWAYS_ALLOWED_CONTEXT_TOOLS);
  for (const toolName of options.alwaysAllowedContextToolNames || []) {
    alwaysAllowedToolNames.add(toolName);
  }
  let connectorsEnabled = false;
  for (const access of effectiveTools) {
    if (!access.enabled) continue;
    if (access.toolFamily === 'connectors') connectorsEnabled = true;
    for (const tool of access.runtimeTools) {
      enabledToolNames.add(tool);
    }
  }

  /**
   * Check whether a tool is permitted for this agent.
   * - Context-internal tools in ALWAYS_ALLOWED_CONTEXT_TOOLS are always allowed.
   * - Connector tools (connector_*) are allowed if the 'connectors' family is enabled.
   * - All other tools are allowed only if they appear in enabledToolNames.
   */
  function isToolPermitted(toolName: string): boolean {
    if (alwaysAllowedToolNames.has(toolName)) {
      return true; // Always allowed — Talk-internal context access
    }
    if (toolName.startsWith('connector_')) {
      return connectorsEnabled;
    }
    return enabledToolNames.has(toolName);
  }

  // Build tool array, filtering by agent's tool permissions.
  const tools: LlmToolDefinition[] = [];

  if (context) {
    for (const tool of context.contextTools) {
      if (isToolPermitted(tool.name)) {
        tools.push(tool);
      }
    }
    for (const tool of context.connectorTools) {
      if (isToolPermitted(tool.name)) {
        tools.push(tool);
      }
    }
  }

  // TODO: Add agent's own tools here once they're available in the execution context
  // For now, assume they're passed via executeToolCall handler

  // -----------
  // Step 4: Build LLM messages
  // -----------
  const messages: LlmMessage[] = [];

  // Build system prompt and push as first message
  let systemPrompt = '';
  if (context) {
    // Talk context + agent system prompt
    systemPrompt = context.systemPrompt;
    if (agent.system_prompt) {
      systemPrompt += '\n\n' + agent.system_prompt;
    }
  } else {
    // Main channel: just agent's system prompt
    systemPrompt = agent.system_prompt || '';
  }

  if (systemPrompt) {
    messages.push({ role: 'system', content: systemPrompt });
  }

  // Add Talk history if in Talk context
  if (context && context.history.length > 0) {
    messages.push(...context.history);
  }

  // Add user message
  messages.push({
    role: 'user',
    content: userMessage,
  });

  // -----------
  // Step 5: Stream LLM response
  // -----------
  emit({
    type: 'started',
    runId: options.runId,
    agentId,
    providerId: agent.provider_id,
    modelId: agent.model_id,
  });

  let finalContent = '';
  let accumulatedTokens = {
    inputTokens: 0,
    outputTokens: 0,
    estimatedCostUsd: 0,
  };
  let lastProviderStopReason: string | null = null;
  let usedToolIterationFallback = false;
  // Track the most recent turn's provider_data so the executor can
  // persist it in the trusted replay store. Only the FINAL turn's
  // codex items are kept (mid-loop tool-call turns get their reasoning
  // replaced on the next iteration anyway).
  let latestProviderData: AgentExecutionResult['providerData'] | undefined;

  const maxToolIterations = Math.max(1, options.maxToolIterations ?? 10);
  let codexContinuationCount = 0;

  try {
    for (let iteration = 0; iteration < maxToolIterations; iteration++) {
      // T6: enforce the run-scoped budget at the step boundary. If the run has
      // burned its external-await budget — e.g. a dead provider eating tool
      // timeouts round after round — stop here with a graceful labeled error
      // instead of starting another LLM + tool round. The queue watchdog is
      // the harder, detached backstop below this.
      if (options.budget && options.budget.remainingMs() <= 0) {
        const errorMessage =
          'The run exceeded its time budget before producing a final response.';
        emit({ type: 'failed', errorCode: 'deadline_exceeded', errorMessage });
        throw new TalkExecutorError('deadline_exceeded', errorMessage);
      }
      // Force a tool call only on the FIRST iteration. Once the agent
      // has been pushed into picking a tool, subsequent iterations
      // resolve normally (the agent may need to call more tools or
      // settle on a final assistant turn).
      const forceToolUseThisTurn =
        iteration === 0 &&
        (options.forceToolUseOnFirstIteration ?? false) &&
        tools.length > 0;
      const stream = streamLlmResponse(
        providerConfig,
        secret,
        agent.model_id,
        messages,
        {
          tools,
          maxOutputTokens: defaultMaxOutputTokens,
          signal: options.signal,
          forceToolUse: forceToolUseThisTurn,
        },
      );

      // Accumulate this turn's content and tool calls from the stream
      let turnTextContent = '';
      const pendingToolCalls = new Map<
        string,
        { name: string; argumentsJson: string }
      >();
      let stopReason = 'end_turn';

      for await (const event of stream) {
        if (options.signal?.aborted) {
          emit({ type: 'cancelled' });
          const abortErr =
            options.signal.reason instanceof Error
              ? options.signal.reason
              : Object.assign(new Error('Agent execution was cancelled'), {
                  name: 'AbortError',
                });
          throw abortErr;
        }

        if (event.type === 'text_delta') {
          turnTextContent += event.text;
          emit({ type: 'text_delta', text: event.text || '' });
        } else if (event.type === 'tool_call_start') {
          if (event.toolCall) {
            pendingToolCalls.set(event.toolCall.id, {
              name: event.toolCall.name,
              argumentsJson: '',
            });
          }
        } else if (event.type === 'tool_call_delta') {
          if (event.toolCall) {
            const current = pendingToolCalls.get(event.toolCall.id);
            if (current) {
              if (event.toolCall.argumentsDelta) {
                current.argumentsJson += event.toolCall.argumentsDelta;
              }
              if (event.toolCall.arguments) {
                current.argumentsJson = event.toolCall.arguments;
              }
            }
          }
        } else if (event.type === 'done') {
          stopReason = event.stopReason || 'end_turn';
        } else if (event.type === 'usage') {
          accumulatedTokens = {
            inputTokens:
              accumulatedTokens.inputTokens + (event.usage?.inputTokens || 0),
            outputTokens:
              accumulatedTokens.outputTokens + (event.usage?.outputTokens || 0),
            estimatedCostUsd: 0,
          };
          emit({
            type: 'usage',
            inputTokens: event.usage?.inputTokens || 0,
            outputTokens: event.usage?.outputTokens || 0,
            estimatedCostUsd: 0,
          });
        } else if (event.type === 'provider_data') {
          if (event.providerData) {
            latestProviderData = event.providerData;
          }
        }
      }

      finalContent += turnTextContent;
      lastProviderStopReason = normalizeProviderStopReason(stopReason);
      const reachedToolIterationLimit = iteration === maxToolIterations - 1;

      // If no tool calls or no executeToolCall callback, we're done.
      // Anthropic stop reason: 'tool_use', OpenAI finish reason: 'tool_calls'
      const isToolUseStop =
        stopReason === 'tool_use' || stopReason === 'tool_calls';
      if (
        pendingToolCalls.size === 0 ||
        !options.executeToolCall ||
        !isToolUseStop
      ) {
        // Codex continuation retry: an `incomplete` response with
        // captured encrypted reasoning means the model produced
        // commentary or thinking-only output and needs one more turn.
        // Feed the partial assistant message + reasoning blob back in
        // so the backend continues from where it left off. Bounded by
        // MAX_CODEX_CONTINUATIONS; the iteration counter is rewound so
        // the continuation doesn't burn the tool-iteration budget.
        const codexShouldContinue =
          providerConfig.apiFormat === 'codex_responses' &&
          stopReason === 'incomplete' &&
          Boolean(
            latestProviderData?.codexReasoningItems?.length ||
            latestProviderData?.codexMessageItems?.length,
          ) &&
          codexContinuationCount < MAX_CODEX_CONTINUATIONS;
        if (codexShouldContinue) {
          codexContinuationCount += 1;
          messages.push({
            role: 'assistant',
            content: turnTextContent || '',
            providerData: latestProviderData,
          });
          iteration -= 1;
          continue;
        }
        break;
      }

      // Build assistant message with text + tool_use content blocks
      const assistantContent: LlmContentBlock[] = [];
      if (turnTextContent) {
        assistantContent.push({ type: 'text', text: turnTextContent });
      }
      for (const [id, call] of Array.from(pendingToolCalls.entries())) {
        let parsedInput: unknown = {};
        try {
          parsedInput = call.argumentsJson
            ? JSON.parse(call.argumentsJson)
            : {};
        } catch {
          parsedInput = {};
        }
        assistantContent.push({
          type: 'tool_use',
          id,
          name: call.name,
          input: parsedInput,
        });
      }
      messages.push({ role: 'assistant', content: assistantContent });

      // Execute this turn's tool calls and collect their results. The dispatch
      // strategy — parallel contiguous read-only runs, every other tool a
      // sequential barrier, results appended in batch order — is documented at
      // the dispatch loop below.
      const toolResults: Array<{
        id: string;
        name: string;
        result: string;
        isError: boolean;
      }> = [];

      // Guaranteed defined: the loop broke above when executeToolCall was
      // absent (isToolUseStop guard). Captured into a const so the closure
      // below sees the narrowed, non-undefined type.
      const executeToolCall = options.executeToolCall;

      const toolBatch = Array.from(pendingToolCalls.entries()).map(
        ([id, call]) => {
          let parsedArgs: Record<string, unknown> = {};
          try {
            parsedArgs = call.argumentsJson
              ? JSON.parse(call.argumentsJson)
              : {};
          } catch {
            parsedArgs = {};
          }
          return { id, name: call.name, parsedArgs };
        },
      );

      // Run one tool call: emit its lifecycle events and resolve to a result
      // record. Never throws — executor rejections become isError results,
      // matching the prior sequential behavior exactly.
      const runToolCall = async (entry: {
        id: string;
        name: string;
        parsedArgs: Record<string, unknown>;
      }): Promise<{
        id: string;
        name: string;
        result: string;
        isError: boolean;
      }> => {
        emit({
          type: 'tool_call',
          toolName: entry.name,
          arguments: entry.parsedArgs,
        });
        const toolStartedAt = Date.now();
        try {
          const { result, isError } = await executeToolCall(
            entry.name,
            entry.parsedArgs,
          );
          emit({
            type: 'tool_result',
            toolName: entry.name,
            result,
            isError,
            durationMs: Date.now() - toolStartedAt,
          });
          return {
            id: entry.id,
            name: entry.name,
            result,
            isError: !!isError,
          };
        } catch (err) {
          const errorMsg = String(err);
          emit({
            type: 'tool_result',
            toolName: entry.name,
            result: errorMsg,
            isError: true,
            durationMs: Date.now() - toolStartedAt,
          });
          return {
            id: entry.id,
            name: entry.name,
            result: errorMsg,
            isError: true,
          };
        }
      };

      // Honor a cancel that landed after the model emitted tool calls, before
      // we launch any (possibly many) tool executions. Mirrors the stream
      // loop's abort handling above so a mid-turn cancel can't fan out a batch
      // of provider/DB work that the run is about to discard.
      if (options.signal?.aborted) {
        emit({ type: 'cancelled' });
        const abortErr =
          options.signal.reason instanceof Error
            ? options.signal.reason
            : Object.assign(new Error('Agent execution was cancelled'), {
                name: 'AbortError',
              });
        throw abortErr;
      }

      // Dispatch in batch order. A maximal run of CONSECUTIVE read-only tools
      // executes concurrently (bounded by READ_ONLY_TOOL_CONCURRENCY); any
      // other tool is a BARRIER — it drains the preceding read run, then runs
      // sequentially. Reads therefore never cross a write, so the model never
      // sees a read that ran "before" an earlier-in-batch write, and results
      // stay in batch (tool_use id) order — byte-stable for prompt caching
      // (T4 / Lane A).
      let readRun: typeof toolBatch = [];
      const flushReadRun = async (): Promise<void> => {
        if (readRun.length === 0) return;
        const runResults = await runBoundedInOrder(
          readRun,
          READ_ONLY_TOOL_CONCURRENCY,
          runToolCall,
        );
        for (const result of runResults) toolResults.push(result);
        readRun = [];
      };
      for (const entry of toolBatch) {
        if (READ_ONLY_PARALLELIZABLE_TOOLS.has(entry.name)) {
          readRun.push(entry);
        } else {
          await flushReadRun();
          toolResults.push(await runToolCall(entry));
        }
      }
      await flushReadRun();

      // Append tool results as messages.
      // For Anthropic: tool_result blocks inside a single role:'tool' message
      //   (buildAnthropicRequest converts role:'tool' with LlmContentBlock[] to
      //    a user message with tool_result blocks)
      // For OpenAI + Codex Responses: individual role:'tool' messages with
      //   toolCallId. The Codex backend expects function_call_output.output to
      //   be a plain string; sending tool_result blocks here would leave the
      //   adapter forced to emit output as a content-parts array, which the
      //   chatgpt.com/backend-api/codex endpoint silently drops — Codex then
      //   complains "No tool output found for function call call_xxx" on the
      //   next turn even though we sent one.
      if (
        providerConfig.apiFormat === 'openai_chat_completions' ||
        providerConfig.apiFormat === 'codex_responses'
      ) {
        for (const tr of toolResults) {
          messages.push({
            role: 'tool',
            content: tr.result,
            toolCallId: tr.id,
          });
        }
      } else {
        // Anthropic: structured tool_result blocks
        const toolResultBlocks: LlmContentBlock[] = toolResults.map((tr) => ({
          type: 'tool_result' as const,
          toolUseId: tr.id,
          content: tr.result,
          isError: tr.isError,
        }));
        messages.push({ role: 'tool', content: toolResultBlocks });
      }

      if (reachedToolIterationLimit) {
        if (options.toolIterationLimitFallback) {
          finalContent = options.toolIterationLimitFallback;
          usedToolIterationFallback = true;
        }
        break;
      }

      // Reset turn text for next iteration — the LLM will produce new content
      // finalContent already accumulated, next turn appends more
    }
  } catch (err) {
    if (err instanceof LlmClientError) {
      // TODO: Implement fallback logic here
      // For now, just fail
      emit({
        type: 'failed',
        errorCode: err.failureClass || 'LLM_ERROR',
        errorMessage: err.message,
      });
      throw err;
    }
    throw err;
  }

  // -----------
  // Step 6: Emit completion
  // -----------
  if (!usedToolIterationFallback) {
    const finalContentTrimmed = finalContent.trim();
    const completedCleanly =
      finalContentTrimmed.length > 0 &&
      Boolean(
        lastProviderStopReason &&
        CLEAN_PROVIDER_STOP_REASONS.has(lastProviderStopReason),
      );

    if (!completedCleanly) {
      const incomplete = buildIncompleteCompletion({
        content: finalContent,
        providerStopReason: lastProviderStopReason,
      });
      emit({
        type: 'failed',
        errorCode: 'incomplete_response',
        errorMessage: incomplete.errorMessage,
        completion: incomplete,
      });
      throw new TalkExecutorError(
        'incomplete_response',
        incomplete.errorMessage,
        {
          metadata: incomplete,
        },
      );
    }
  }

  const completion = {
    completionStatus: 'complete' as const,
    providerStopReason: lastProviderStopReason,
    incompleteReason: null,
  };
  emit({
    type: 'completed',
    content: finalContent,
    completion,
  });

  return {
    content: finalContent,
    agentId,
    providerId: agent.provider_id,
    modelId: agent.model_id,
    usage: accumulatedTokens,
    completion,
    providerData: latestProviderData,
  };
}
